In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression

X = np.array([[1, 1], [1, 2], [2, 2], [2, 3]])
y = np.dot(X, np.array([1, 2])) + 3

In [8]:
type(X)

numpy.ndarray

In [9]:
type(X[0])

numpy.ndarray

In [10]:
X.shape

(4, 2)

In [13]:
X[0]

array([1, 1])

In [14]:
X

array([[1, 1],
       [1, 2],
       [2, 2],
       [2, 3]])

In [15]:
type(y)

numpy.ndarray

In [18]:
y

array([ 6,  8,  9, 11])